#!/usr/bin/awk -f

BEGIN {
    FS=":.* # " # Separates the targets into $1 and the comments into $2
    printf "\n  Makefile targets:\n\n"
}

# Matches targets and comments separated by FS
/^[ a-zA-Z_-]+:.* # .*$/ {
    # $1: targets, $2: comments
    printf "    \033[36m%-20s\033[0m %s\n", $1, $2
}

END {
    printf "\n"
}
