#!/bin/bash

PIPE_PATH="/tmp/v.pipe"

if pstree -s $$ | grep -q nvim; then
	# echo "in neovim"
	realpath $* | xargs -n1 nvim --server "$PIPE_PATH" --remote
else
	# echo "Not in neovim"
	if [ "$#" -eq "0" ]; then
		nvim +te --listen "$PIPE_PATH" --startuptime /tmp/nvimstartup
	else
		nvim $* --listen "$PIPE_PATH" --startuptime /tmp/nvimstartup
	fi
fi
